### ISSUE TITLE
Syntax Error: Unexpected Name "var"

### ISSUE THREAD

**Issue by raheelriax** [lemol/umi-plugin-apollo#16]
I am using this plugin with antd-admin pro template. I have created a page using the CLI and ran 
`umi dev` and now i am getting this error

   error  in ./src/pages/.umi/apollo/sample.schema.graphql
   Module build failed (from ./node_modules/graphql-tag/loader.js):
   GraphQLError: Syntax Error: Unexpected Name "var"

    at syntaxError (/home/in01-nbk-502/practice/antd-admin-pro/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.unexpected (/home/in01-nbk-502/practice/antd-admin-pro/node_modules/graphql/language/parser.js:1463:41)
    at Parser.parseDefinition (/home/in01-nbk-502/practice/antd-admin-pro/node_modules/graphql/language/parser.js:157:16)
    at Parser.many (/home/in01-nbk-502/practice/antd-admin-pro/node_modules/graphql/language/parser.js:1518:26)
    at Parser.parseDocument (/home/in01-nbk-502/practice/antd-admin-pro/node_modules/graphql/language/parser.js:111:25)
    at parse (/home/in01-nbk-502/practice/antd-admin-pro/node_modules/graphql/language/parser.js:36:17)
    at parseDocument (/home/in01-nbk-502/practice/antd-admin-pro/node_modules/graphql-tag/src/index.js:129:16)
    at gql (/home/in01-nbk-502/practice/antd-admin-pro/node_modules/graphql-tag/src/index.js:170:10)
    at Object.module.exports (/home/in01-nbk-502/practice/antd-admin-pro/node_modules/graphql-tag/loader.js:45:18)
`

I've traced back this error to graphql-tag and this is the final result which is being passed to 
`gql` in `loader.js`

type Query {
  _empty: String
}

type Mutation {
  _empty: String
}

    var doc = {"kind":"Document","definitions":[{"kind":"ObjectTypeDefinition","name":{"kind":"Name","value":"Query"},"interfaces":[],"directives":[],"fields":[{"kind":"FieldDefinition","name":{"kind":"Name","value":"_empty"},"arguments":[],"type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}},"directives":[]}]},{"kind":"ObjectTypeDefinition","name":{"kind":"Name","value":"Mutation"},"interfaces":[],"directives":[],"fields":[{"kind":"FieldDefinition","name":{"kind":"Name","value":"_empty"},"arguments":[],"type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}},"directives":[]}]}],"loc":{"start":0,"end":68}};
    doc.loc.source = {"body":"type Query {\n  _empty: String\n}\n\ntype Mutation {\n  _empty: String\n}\n","name":"GraphQL request","locationOffset":{"line":1,"column":1}};
  

    var names = {};
    function unique(defs) {
      return defs.filter(
        function(def) {
          if (def.kind !== 'FragmentDefinition') return true;
          var name = def.name.value
          if (names[name]) {
            return false;
          } else {
            names[name] = true;
            return true;
          }
        }
      )
    }
  

      module.exports = doc;
    

**Any idea what went wrong ?**

**Comment by raheelriax** [comment]
Okay So I figured out that what is causing this behavior. This happens If you pass
`mock: true`
in `umi-plugin-apollo`'s configuration. if you change it to
`mock: false` everything works fine.

**Comment by lemol** [comment]
@raheelriax , thank you for reporting.

I found that after umi#2547 we don't need to set the graphql loader in this plugin.

I will fix it and this will make it work including with `mock: true` config.

**Comment by xxx-adi** [comment]
this graphql loader issue seems to be fixed in the latest commit , but the version is not bumped yet. so the plugin installed through npm is still the buggy version 0.0.17 @lemol
