### ISSUE TITLE
Yarn Add Fails

### ISSUE THREAD

**Issue by ial0** [lemol/umi-plugin-apollo#28]
When installing via `yarn add umi-plugin-apollo` I get this error,
```
success Saved lockfile.
success Saved 411 new dependencies.
info Direct dependencies
└─ umi-plugin-apollo@0.0.18
info All dependencies
├─ @apollo/react-hoc@3.1.5
....
├─ yeoman-generator@4.0.1
└─ zen-observable-ts@0.8.21
$ umi generate tmp
Path must be a string.
TypeError: Path must be a string.
    at Function.resolveSync [as sync] (/home/ial/Devel/sas/web/node_modules/@umijs/utils/node_modules/resolve/lib/sync.js:53:15)
    at /home/ial/Devel/sas/web/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:90:29
    at Array.map (<anonymous>)
    at getPluginsOrPresets (/home/ial/Devel/sas/web/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:89:99)
    at resolvePlugins (/home/ial/Devel/sas/web/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:183:19)
    at new Service (/home/ial/Devel/sas/web/node_modules/@umijs/core/lib/Service/Service.js:183:59)
    at new Service (/home/ial/Devel/sas/web/node_modules/umi/lib/ServiceWithBuiltIn.js:50:5)
    at /home/ial/Devel/sas/web/node_modules/umi/lib/cli.js:98:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/ial/Devel/sas/web/node_modules/umi/lib/cli.js:53:103)
```
Any ideas?

**Comment by treffiletti** [comment]
+1 Same issue here.

**Comment by askurat** [comment]
@ial0 did you ever get this working?

**Comment by beyondouyuan** [comment]
+1 same issue here

umi verssion 3.x

**Comment by cospin** [comment]
Any workarounds for this?
